export const teamsInitial = [
  {
    name: 'Atlanta Braves',
    value: 75,
    league: 'MLB',
  },
  {
    name: 'Tampa Bay Rays',
    value: 75,
    league: 'MLB',
  },
  {
    name: 'Los Angeles Dodgers',
    value: 50,
    league: 'MLB',
  },
  {
    name: 'Houston Astros',
    value: 50,
    league: 'MLB',
  },
  {
    name: 'Texas Rangers',
    value: 50,
    league: 'MLB',
  },
  {
    name: 'New York Yankees',
    value: 40,
    league: 'MLB',
  },
  {
    name: 'Toronto Blue Jays',
    value: 35,
    league: 'MLB',
  },
  {
    name: 'Philadelphia Phillies',
    value: 15,
    league: 'MLB',
  },
  {
    name: 'Arizona Diamondbacks',
    value: 25,
    league: 'MLB',
  },
  {
    name: 'San Francisco Giants',
    value: 20,
    league: 'MLB',
  },
  {
    name: 'Minnesota Twins',
    value: 15,
    league: 'MLB',
  },
  {
    name: 'Baltimore Orioles',
    value: 30,
    league: 'MLB',
  },
  {
    name: 'San Diego Padres',
    value: 5,
    league: 'MLB',
  },
  {
    name: 'Milwaukee Brewers',
    value: 10,
    league: 'MLB',
  },
  {
    name: 'Miami Marlins',
    value: 5,
    league: 'MLB',
  },
  {
    name: 'Los Angeles Angels',
    value: 2,
    league: 'MLB',
  },
  {
    name: 'Cleveland Guardians',
    value: 1,
    league: 'MLB',
  },
  {
    name: 'Cincinatti Reds',
    value: 5,
    league: 'MLB',
  },
  {
    name: 'Seattle Mariners',
    value: 1,
    league: 'MLB',
  },
  {
    name: 'Chicago Cubs',
    value: 1,
    league: 'MLB',
  },
  {
    name: 'Pittsburgh Pirates',
    value: 1,
    league: 'MLB',
  },
  {
    name: 'New York Mets',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Boston Red Sox',
    value: 1,
    league: 'MLB',
  },
  {
    name: 'St. Louis Cardinals',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Detroit Tigers',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Washington Nationals',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Chicago White Sox',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Colorado Rockies',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Kansas City Royals',
    value: 0,
    league: 'MLB',
  },
  {
    name: 'Oakland Athletics',
    value: 0,
    league: 'MLB',
  },
  { name: 'Kansas City Chiefs', value: 80, league: 'NFL' },
  { name: 'Philadelphia Eagles', value: 70, league: 'NFL' },
  { name: 'Buffalo Bills', value: 65, league: 'NFL' },
  { name: 'San Francisco 49ers', value: 60, league: 'NFL' },
  { name: 'Cincinatti Bengals', value: 60, league: 'NFL' },
  { name: 'Dallas Cowboys', value: 30, league: 'NFL' },
  { name: 'New York Jets', value: 25, league: 'NFL' },
  { name: 'Baltimore Ravens', value: 25, league: 'NFL' },
  { name: 'Detroit Lions', value: 15, league: 'NFL' },
  { name: 'Miami Dolphins', value: 15, league: 'NFL' },
  {
    name: 'Jacksonville Jaguars',
    value: 15,
    league: 'NFL',
  },
  {
    name: 'Los Angeles Chargers',
    value: 20,
    league: 'NFL',
  },
  {
    name: 'Seattle Seahawks',
    value: 10,
    league: 'NFL',
  },
  {
    name: 'Cleveland Browns',
    value: 10,
    league: 'NFL',
  },
  {
    name: 'New Orleans Saints',
    value: 1,
    league: 'NFL',
  },
  {
    name: 'Minnesota Vikings',
    value: 5,
    league: 'NFL',
  },
  {
    name: 'Denver Broncos',
    value: 3,
    league: 'NFL',
  },
  {
    name: 'Green Bay Packers',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'New York Giants',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Chicago Bears',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Pittsburgh Steelers',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'New England Patriots',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Las Vegas Raiders',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Los Angeles Rams',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Atlanta Falcons',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Washington Commanders',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Carolina Panthers',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Indianapolis Colts',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Tennessee Titans',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Tampa Bay Buccaneers',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Houston Texans',
    value: 0,
    league: 'NFL',
  },
  {
    name: 'Arizona Cardinals',
    value: 0,
    league: 'NFL',
  },
  { name: 'Boston Celtics', value: 60, league: 'NBA' },
  { name: 'Denver Nuggets', value: 60, league: 'NBA' },
  { name: 'Milwaukee Bucks', value: 50, league: 'NBA' },
  { name: 'Phoenix Suns', value: 40, league: 'NBA' },
  { name: 'Miami Heat', value: 40, league: 'NBA' },
  { name: 'Golden State Warriors', value: 20, league: 'NBA' },
  { name: 'Los Angeles Lakers', value: 20, league: 'NBA' },
  { name: 'Philadelphia 76ers', value: 30, league: 'NBA' },
  { name: 'Los Angeles Clippers', value: 25, league: 'NBA' },
  { name: 'Dallas Mavericks', value: 10, league: 'NBA' },
  { name: 'Memphis Grizzlies', value: 5, league: 'NBA' },
  { name: 'Cleveland Cavaliers', value: 5, league: 'NBA' },
  { name: 'New Orleans Pelicans', value: 1, league: 'NBA' },
  { name: 'Sacramento Kings', value: 1, league: 'NBA' },
  { name: 'New York Knicks', value: 1, league: 'NBA' },
  { name: 'Minnesota Timberwolves', value: 0, league: 'NBA' },
  { name: 'Atlanta Hawks', value: 0, league: 'NBA' },
  { name: 'Oklahoma City Thunder', value: 0, league: 'NBA' },
  { name: 'Toronto Raptors', value: 0, league: 'NBA' },
  { name: 'Brooklyn Nets', value: 0, league: 'NBA' },
  { name: 'Chicago Bulls', value: 0, league: 'NBA' },
  { name: 'Portland Trail Blazers', value: 0, league: 'NBA' },
  { name: 'Utah Jazz', value: 0, league: 'NBA' },
  { name: 'San Antonio Spurs', value: 0, league: 'NBA' },
  { name: 'Orlando Magic', value: 0, league: 'NBA' },
  { name: 'Indiana Pacers', value: 0, league: 'NBA' },
  { name: 'Houston Rockets', value: 0, league: 'NBA' },
  { name: 'Washington Wizards', value: 0, league: 'NBA' },
  { name: 'Charlotte Hornets', value: 0, league: 'NBA' },
  { name: 'Detroit Pistons', value: 0, league: 'NBA' },
  { name: 'Colorado Avalanche', value: 60, league: 'NHL' },
  { name: 'Edmonton Oilers', value: 40, league: 'NHL' },
  { name: 'Carolina Hurricanes', value: 35, league: 'NHL' },
  { name: 'New Jersey Devils', value: 40, league: 'NHL' },
  { name: 'Toronto Maple Leafs', value: 1, league: 'NHL' },
  { name: 'Vegas Golden Knights', value: 60, league: 'NHL' },
  { name: 'Boston Bruins', value: 20, league: 'NHL' },
  { name: 'New York Rangers', value: 10, league: 'NHL' },
  { name: 'Dallas Stars', value: 30, league: 'NHL' },
  { name: 'Tampa Bay Lightning', value: 5, league: 'NHL' },
  { name: 'Carolina Panthers', value: 1, league: 'NHL' },
  { name: 'Sacramento Kings', value: 0, league: 'NHL' },
  { name: 'Minnesota Wild', value: 0, league: 'NHL' },
  { name: 'Pittsburgh Penguins', value: 0, league: 'NHL' },
  { name: 'Buffalo Sabres', value: 0, league: 'NHL' },
  { name: 'Calgary Flames', value: 0, league: 'NHL' },
  { name: 'Seattle Kraken', value: 0, league: 'NHL' },
  { name: 'New York Islanders', value: 1, league: 'NHL' },
  { name: 'Ottawa Senators', value: 0, league: 'NHL' },
  { name: 'St. Louis Blues', value: 0, league: 'NHL' },
  { name: 'Vancouver Canucks', value: 0, league: 'NHL' },
  { name: 'Detroit Red Wings', value: 0, league: 'NHL' },
  { name: 'Winnipeg Jets', value: 0, league: 'NHL' },
  { name: 'Washington Capitals', value: 0, league: 'NHL' },
  { name: 'Nashville Predators', value: 0, league: 'NHL' },
  { name: 'Chicago Blackhawks', value: 0, league: 'NHL' },
  { name: 'Columbus Blue Jackets', value: 0, league: 'NHL' },
  { name: 'Philadelphia Flyers', value: 0, league: 'NHL' },
  { name: 'Montreal Canadiens', value: 0, league: 'NHL' },
  { name: 'Anaheim Ducks', value: 0, league: 'NHL' },
];
