// export const red  = '#DA2929'
export const red = ' #F88B60'
export const blue = '#013369'
export const mediumBlue = '#C0CCD9'
export const lightBlue = '#DFE5EC'
export const mobileBreakPoint = '768px'