/**
 * Application global constants.
 */
module.exports = {
  TEST_ROSTER: [
    {
      bench1: { name: 'Chicago White Sox', id: '105', value: 2 },
      bench2: { name: 'Pittsburgh Penguins', id: '323', value: 4 },
      bench3: { name: 'Columbus Blue Jackets', id: '309', value: 4 },
      cash: 15,
      email: 'evan@evanklane.com',
      flex1: { name: 'Milwaukee Brewers', id: '116', value: 15 },
      league1: { name: 'Atlanta Braves', id: '102', value: 44 },
      league2: { name: 'Buffalo Bills', id: '204', value: 60 },
      league3: { name: 'Carolina Hurricanes', id: '306', value: 46 },
      league4: { name: 'Detroit Pistons', id: '409', value: 10 },
      name: 'Evan',
      tempId: 1,
    }, {
      bench1: { name: 'Washington Nationals', id: '130', value: 10 },
      bench2: { name: 'New Orleans Pelicans', id: '419', value: 5 },
      bench3: { name: 'New York Knicks', id: '420', value: 5 },
      cash: 50,
      email: 'gaurav.v.shastri@gmail.com',
      flex1: { name: 'Los Angeles Rams', id: '219', value: 53 },
      league1: { name: 'Cincinnati Reds', id: '107', value: 14 },
      league2: { name: 'Denver Broncos', id: '210', value: 16 },
      league3: { name: 'Florida Panthers', id: '313', value: 33 },
      league4: { name: 'Los Angeles Lakers', id: '414', value: 14 },
      name: 'Gaurav',
      tempId: 2,
    }, {
      bench1: { name: 'New Jersey Devils', id: '318', value: 1 },
      bench2: { name: 'Washington Commanders', id: '232', value: 15 },
      bench3: { name: 'Miami Marlins', id: '115', value: 20 },
      cash: 71,
      email: 'narotskya@gmail.com',
      flex1: { name: 'Buffalo Sabres', id: '304', value: 1 },
      league1: { name: 'Kansas City Royals', id: '112', value: 24 },
      league2: { name: 'Detroit Lions', id: '211', value: 14 },
      league3: { name: 'Edmonton Oilers', id: '312', value: 10 },
      league4: { name: 'Minnesota Timberwolves', id: '418', value: 44 },
      name: 'Andy',
      tempId: 3,
    }, {
      bench1: { name: 'Philadelphia Phillies', id: '121', value: 16 },
      bench2: { name: 'Anaheim Ducks', id: '301', value: 14 },
      bench3: { name: 'New England Patriots', id: '222', value: 14 },
      cash: 1,
      email: 'timharper1121@gmail.com',
      flex1: { name: 'Minnesota Twins', id: '117', value: 11 },
      league1: { name: 'New York Mets', id: '119', value: 10 },
      league2: { name: 'Dallas Cowboys', id: '209', value: 44 },
      league3: { name: 'Montreal Canadiens', id: '316', value: 66 },
      league4: { name: 'Memphis Grizzlies', id: '415', value: 24 },
      name: 'Tim',
      tempId: 4,
    }, {
      bench1: { name: 'San Diego Padres', id: '123', value: 11 },
      bench2: { name: 'Seattle Mariners', id: '125', value: 11 },
      bench3: { name: 'Winnipeg Jets', id: '332', value: 11 },
      cash: 112,
      email: 'hayden.freedman@gmail.com',
      flex1: { name: 'Cincinnati Bengals', id: '207', value: 11 },
      league1: { name: 'Boston Red Sox', id: '104', value: 11 },
      league2: { name: 'Cleveland Browns', id: '208', value: 11 },
      league3: { name: 'Minnesota Wild', id: '315', value: 11 },
      league4: { name: 'Houston Rockets', id: '411', value: 11 },
      name: 'Hayden',
      tempId: 5,
    },
    {
      bench1: { name: 'Texas Rangers', id: '128', value: 11 },
      bench2: { name: 'Calgary Flames', id: '305', value: 11 },
      bench3: { name: 'New York Jets', id: '225', value: 11 },
      cash: 112,
      email: 'wtaylorfrank@gmail.com',
      flex1: { name: 'Arizona Coyotes', id: '302', value: 11 },
      league1: { name: 'Chicago Cubs', id: '106', value: 11 },
      league2: { name: 'Philadelphia Eagles', id: '226', value: 11 },
      league3: { name: 'Dallas Stars', id: '310', value: 11 },
      league4: { name: 'Charlotte Hornets', id: '404', value: 11 },
      name: 'Frank',
      tempId: 6,
    }, {
      bench1: { name: 'Los Angeles Angels', id: '113', value: 11 },
      bench2: { name: 'Tennessee Titans', id: '231', value: 11 },
      bench3: { name: 'Atlanta Hawks', id: '401', value: 11 },
      cash: 112,
      email: 'gzwaag94@gmail.com',
      flex1: { name: 'Miami Dolphins', id: '220', value: 11 },
      league1: { name: 'Oakland Athletics', id: '120', value: 11 },
      league2: { name: 'San Francisco 49ers', id: '228', value: 11 },
      league3: { name: 'Vancouver Canucks', id: '329', value: 11 },
      league4: { name: 'Miami Heat', id: '416', value: 11 },
      name: 'GW',
      tempId: 7,
    }, {
      bench1: { name: 'Colorado Rockies', id: '109', value: 11 },
      bench2: { name: 'Indianapolis Colts', id: '214', value: 11 },
      bench3: { name: 'San Antonio Spurs', id: '427', value: 11 },
      cash: 112,
      email: 'RyanBlackMedia@gmail.com',
      flex1: { name: 'Houston Texans', id: '213', value: 11 },
      league1: { name: 'Tampa Bay Rays', id: '127', value: 11 },
      league2: { name: 'Carolina Panthers', id: '205', value: 11 },
      league3: { name: 'St. Louis Blues', id: '326', value: 11 },
      league4: { name: 'Cleveland Cavaliers', id: '406', value: 11 },
      name: 'Ryan',
      tempId: 8,
    }, {
      bench1: { name: 'Los Angeles Dodgers', id: '114', value: 11 },
      bench2: { name: 'Oklahoma City Thunder', id: '421', value: 11 },
      bench3: { name: 'Colorado Avalanche', id: '308', value: 11 },
      cash: 112,
      email: 'Richard.Shu4@gmail.com',
      flex1: { name: 'Las Vegas Raiders', id: '217', value: 11 },
      league1: { name: 'New York Yankees', id: '118', value: 11 },
      league2: { name: 'New Orleans Saints', id: '223', value: 11 },
      league3: { name: 'Seattle Kraken', id: '325', value: 11 },
      league4: { name: 'Indiana Pacers', id: '412', value: 11 },
      name: 'Richard',
      tempId: 9,
    }, {
      bench1: { name: 'Denver Nuggets', id: '408', value: 11 },
      bench2: { name: 'Milwaukee Bucks', id: '417', value: 11 },
      bench3: { name: 'Ottawa Senators', id: '321', value: 11 },
      cash: 200,
      email: 'maxblackpittsburgh4@gmail.com',
      flex1: { name: 'Chicago Blackhawks', id: '307', value: 11 },
      league1: { name: 'Detroit Tigers', id: '110', value: 11 },
      league2: { name: 'New York Giants', id: '224', value: 11 },
      league3: { name: 'San Jose Sharks', id: '324', value: 11 },
      league4: { name: 'Sacramento Kings', id: '426', value: 11 },
      name: 'Max',
      tempId: 10,
    },
  ],
};
